### PR TITLE
fix: make nix build run

### LINKED ISSUE #1: nix-build failing - attribute 'yarn-static' missing
``` console
$ nix-build --show-trace
error: while evaluating 'mkAttrOverridable' at /nix/store/kf3adfr28xj77rmqbzy98qil86380zgv-nixpkgs-src/lib/customisation.nix:133:33, called from undefined position:
while evaluating 'makeOverridable' at /nix/store/kf3adfr28xj77rmqbzy98qil86380zgv-nixpkgs-src/lib/customisation.nix:67:24, called from /nix/store/kf3adfr28xj77rmqbzy98qil86380zgv-nixpkgs-src/lib/customisation.nix:133:36:
while evaluating anonymous function at /nix/store/kf3adfr28xj77rmqbzy98qil86380zgv-nixpkgs-src/lib/customisation.nix:133:53, called from /nix/store/kf3adfr28xj77rmqbzy98qil86380zgv-nixpkgs-src/lib/customisation.nix:69:16:
while evaluating the attribute 'offlinecache' at {...}/adrestia-multisig-coordination/nix/packages.nix:9:40:
attribute 'yarn-static' missing, at {...}/adrestia-multisig-coordination/nix/packages.nix:9:14

```

### PR DESCRIPTION
**Pull request by AlanVerbner**
Closes #1 

*Note: This one requires #9 to be merged*

### CODE REVIEW

**Review by rhyslbw — CHANGES_REQUESTED** [review]
It would be best to run the e2e test suite against the nix build too as part of the CI workflow. This will catch any issues early and provide assurance over the supported executables.

**Comment by AlanVerbner** [comment]
@rhyslbw are you suggesting to use Hydra or just a step in the CI process?

**Comment by rhyslbw** [comment]
Just a step in the Github CI workflow @AlanVerbner

**Comment by rhyslbw** [comment]
@AlanVerbner https://github.com/input-output-hk/adrestia-multisig-coordination/pull/22 unblocks this

**Review by rhyslbw — APPROVED** [review]

**Pull request merged**
